config/routes.rb
Rails.application.routes.draw do

  resources :companies do
    resources :reviews, only: [:new, :create]
  end

  root to: 'welcome#index'
  devise_for :users
  resources :users

  get 'search' => 'companies#search'

  get "*path", :to => "application#routing_error"
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :reviews

  def average_sentiment()
    reviews = self.reviews
    num_reviews = reviews.length
    running_average = 0

    reviews.each do |review|
      running_average += (1.0/num_reviews)*review.sentiment_score
    end

    puts 'Running average ' + running_average.to_s
    self.average_sentiment_score = running_average

    if running_average > 0
      label = 'positive'
    elsif running_average == 0
      label = 'neutral'
    else
      label = 'negative'
    end
    self.average_sentiment_label = label

    self.save()
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :company
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.hash_email(email_addr)
    hashed_email = Digest::SHA1.hexdigest(email_addr.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  rescue_from ActionController::RoutingError, :with => :render_not_found

  def routing_error
    raise ActionController::RoutingError.new(params[:path])
  end

  def render_not_found
    redirect_to root_path
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    redirect_to(:controller=>"welcome", :action=>"index")
  end

  def search
    @company = Company.find_by_name(params[:q].downcase)
    if @company.nil? and params[:q].blank?
      redirect_to(:controller=>"welcome", :action=>"index")
    elsif @company.nil?
      redirect_to(:action=>"new", :name =>params[:q].downcase)
    else
      redirect_to(:action=>"show", :id =>@company.id)
    end
  end

  def show
    @logo_url = get_company_logo_url(@company.name)
    @company.average_sentiment()
    respond_with(@company)
  end

  def new
    @name = params[:name]
    @company = Company.new
    respond_with(@company)
  end

  def edit
    redirect_to(:action=>"show", :id=>params[:id])
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      #force downcase
      params[:company][:name] = params[:company][:name].downcase
      params.require(:company).permit(:name, :description)
    end

    def get_company_logo_url(company_name)
      require 'image_suckr'
      suckr = ImageSuckr::GoogleSuckr.new
      url = suckr.get_image_url({"q" => company_name + " logo", "rsz" => 1})
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_filter :check_logged_in, only: [:new, :create]
  respond_to :html, :xml, :json

  def index
    @reviews = Review.all
    respond_with(@reviews)
  end

  def show
    respond_with(@review)
  end

  def new
    @company = Company.find(params[:company_id])
    @review = Review.new
    respond_with(@review)
  end

  def edit
  end

  def create
    @company = Company.find(params[:company_id])
    @review = Review.new(review_params)
    @review.encrypted_key = User.hash_email(current_user.email)

    #result = run_sentiment_analysis(@review.content)
    #@review.sentiment_label = result[:sentiment]
    #@review.sentiment_score = result[:score]
    if @review.sentiment_label == 'positive'
      @review.sentiment_score = 1.0
    elsif @review.sentiment_label == 'neutral'
      @review.sentiment_score = 0.0
    else
      @review.sentiment_score = -1.0
    end

    if @review.save
        @company.reviews.append(@review)
        @company.save
        flash[:notice] = 'Review was successfully created.' if @review.save
    end

    respond_with(@company)
  end

  def update
    flash[:notice] = 'Review was successfully updated.' if @review.update(review_params)
    respond_with(@review)
  end

  def destroy
    @review.destroy
    respond_with(@review)
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:content, :sentiment_label)
    end

    def check_logged_in
      if !current_user
        redirect_to(new_user_session_path)
      end
    end

    def run_sentiment_analysis(review_content)
      api_key = '57a09ad8e5e23b3d3b9e83c780a699e7a1a8650e' #lol secure
      url = 'http://access.alchemyapi.com/calls/text/TextGetTextSentiment'
      body = {
        :apikey => api_key,
        :text => review_content,
        :outputMode => 'json',
        :showSourceText => '1'
      }
      response = HTTParty.post(url, :body => body)
      response_content = JSON.parse response.body
      if response_content['status'] == 'ERROR'
        result = {:sentiment => 'neutral', :score => 0}
      else
        result = {
          :sentiment => response_content["docSentiment"]["type"],
          :score => response_content["docSentiment"]["score"]
        }
      end
      return result
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :xml, :json
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    encrypted_key = User.hash_email(@user.email)
    @reviews = Review.where(:encrypted_key => encrypted_key)
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :value => (@name.nil? ? "": @name), :id=>"name" %>
  </div>
  <p>doesn't have a company profile yet. Do you want to create one?</p>

  <div class="actions">
    <%= f.submit "add company", :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing <%=@company.name %>'s Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-8 col-md-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

<script>
//dynamic textarea resizing

var observe;
if (window.attachEvent) {
    observe = function (element, event, handler) {
        element.attachEvent('on'+event, handler);
    };
}
else {
    observe = function (element, event, handler) {
        element.addEventListener(event, handler, false);
    };
}
function init () {
    var text = document.getElementById('content');
    function resize () {
        text.style.height = 'auto';
        text.style.height = text.scrollHeight+'px';
    }
    /* 0-timeout to get the already changed text */
    function delayedResize () {
        window.setTimeout(resize, 0);
    }
    observe(text, 'change',  resize);
    observe(text, 'cut',     delayedResize);
    observe(text, 'paste',   delayedResize);
    observe(text, 'drop',    delayedResize);
    observe(text, 'keydown', delayedResize);

    text.focus();
    text.select();
    resize();
}

$(document).ready(function() {
  init();
});
</script>

app/views/companies/show.html.erb
<p class="text-right text-lowercase text-muted" id="notice"><%= notice %></p>
<%= render 'layouts/navigation'%>


<div class="container navbar-push">
  <div class="row wrapper">

    <div class="col-md-3">
      <div class="company-bubble">

          <!-- <img class="logo" src= "<%= @logo_url %>"/> -->
          <h2><%= @company.name %></h2>
          <!--<h4><%= @company.description %></h4>-->
          <h4>Average Sentiment: <b><%= @company.average_sentiment_label %></b> </h4>
          <%= link_to raw("<strong>review</strong>++"), new_company_review_path(@company), :class=>"btn btn-primary", :id=>"new-review"%>

      </div>
    </div>

    <div class="col-md-8 reviews-wrapper" >
      <div>
        <ul class="reviews">

          <% if @company.reviews.any? %>
            <% @company.reviews.order(updated_at: :desc).each do |review| %>
              <li>
                <p><%=review.content %> </p>
                <% sentiment = review.sentiment_label %>
                <% if sentiment == "neutral" %>
                	<p class = "pull-left">Sentiment: <b><font color = gray> <%= review.sentiment_label %> </font></b></p>

                <%elsif sentiment == "negative"%>    
	               <p class = "pull-left">Sentiment: <b> <font color = black><%= review.sentiment_label %></font> </b></p>

	            <%else%>
                <p class = "pull-left">Sentiment: <b> <%= review.sentiment_label %> </b></p>
                <%end%>

                <p class = "pull-right"><b><%=review.created_at.strftime("%m-%d-%Y") %></b> </p>
                <br>
              </li>

            <% end %>
          <% else %>
            <li> 
              <p> No reviews for <b><%= @company.name.capitalize %> </b> have been added. <%= link_to "Add", new_company_review_path(@company) %> your own review 
              </p>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>
</div>

<% if current_user and current_user.name == "admin" %>
  <%= link_to 'Edit', edit_company_path(@company) %> |
  <%= link_to 'Back', companies_path %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-transparent navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to raw('<b>she</b>says'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "she says" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Glassdoor for women in tech" %>">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      	    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      	      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      	        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      	          ga('create', 'UA-55894780-1', 'auto');
      	            ga('send', 'pageview');

    </script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-8 col-md-3">
      <h1 class="thin-text">add <b>your</b> review for <span class="medium-text"><%= @company.name.capitalize %></span></h1>
      <%= form_for [@company, @review] do |f| %>
        <%= f.text_area :content, :rows=>"1", :id=>"content" %>
        </br>
        Your overall sentiment: <%= f.select :sentiment_label, options_for_select(['positive', 'neutral', 'negative']) %>
        </br>
        </br>
      <%= f.submit "create", :class=>"btn btn-primary"%><%= link_to 'back', @company, :class=>"btn btn-link"%>
      <% end %>
    </div>
  </div>
</div>

<script>
//dynamic textarea resizing

var observe;
if (window.attachEvent) {
    observe = function (element, event, handler) {
        element.attachEvent('on'+event, handler);
    };
}
else {
    observe = function (element, event, handler) {
        element.addEventListener(event, handler, false);
    };
}
function init () {
    var text = document.getElementById('content');
    function resize () {
        text.style.height = 'auto';
        text.style.height = text.scrollHeight+'px';
    }
    /* 0-timeout to get the already changed text */
    function delayedResize () {
        window.setTimeout(resize, 0);
    }
    observe(text, 'change',  resize);
    observe(text, 'cut',     delayedResize);
    observe(text, 'paste',   delayedResize);
    observe(text, 'drop',    delayedResize);
    observe(text, 'keydown', delayedResize);

    text.focus();
    text.select();
    resize();
}

$(document).ready(function() {
  init();
});
</script>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

<h2> Your Reviews </h2>
<ul>
<% @reviews.each do |review| %>
  <li><%= review.content %></li>
<% end %>
</ul>